### ISSUE TITLE
Error when trying to run 'javascripting'

### ISSUE THREAD

**Issue by AliceMathews** [workshopper/javascripting#285]
I have installed but when i try to run 'javascripting' i get the following error:
```
module.js:540
throw err;
^
Error: Cannot find module 'split'
at Function.Module._resolveFilname (module.js:538:15)
at Function.Module._load (module.js:468:25)
at Module.require (module.ja:11:17)
at require (internal/module.js:11:18)
at Object.(/home/vagrant/.nvm/versions/node/v8.9.4/lib/node_modules/javascripting/node_modules/workshopper-adventure/lib/print.js:5:15)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module.load (module.js:491:3)
```
Can anyone advise what i've done wrong?

Thanks!

Node v8.9.4
npm v6.11.3
Running on Ubuntu 18.04

**Comment by ledsun** [comment]
I think there was a problem with the installation of javascripting. 
Does the error change if you rerun "npm i -g javascripting"?

**Comment by AliceMathews** [comment]
tried running that instead, it still gives the same error

**Comment by ledsun** [comment]
How about using the latest version of Node?

**Comment by AliceMathews** [comment]
I updated node and it now works - thanks for your help!
