### ISSUE TITLE
can't install globally with WSL

### ISSUE THREAD

**Issue by philshem** [workshopper/javascripting#293]
**Describe the bug**

Installing javascripting in Ubuntu 18.04 (WSL) gives permission errors

**To Reproduce**

Open Ubuntu18.04 terminal running in WSL (Windows Subsystem for Linux)

    sudo apt-get install nodejs npm -y
    npm install -g javascripting

**Expected behavior**

Script completes and I can use terminal command `javascripting`.

**Screenshots**

```
41241 error Linux 4.4.0-43-Microsoft
41242 error argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "javascripting"
41243 error node v8.10.0
41244 error npm  v3.5.2
41245 error path /usr/local/lib/node_modules
41246 error code EACCES
41247 error errno -13
41248 error syscall access
41249 error Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
41249 error  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
41249 error   errno: -13,
41249 error   code: 'EACCES',
41249 error   syscall: 'access',
41249 error   path: '/usr/local/lib/node_modules' }
41250 error Please try running this command again as root/Administrator.
41251 verbose exit [ -13, true ]
```

**Execution environment**

 - WSL (v1) from Windows 10, 4.4.0-43-Microsoft, Ubuntu 18.04
 - npm v3.5.2
 - node v8.10.0

**Comment by philshem** [comment]
For the record, installing on the same platform without the global option `-g` gives this error:

```
47733 error Linux 4.4.0-43-Microsoft
47734 error argv "/usr/bin/node" "/usr/bin/npm" "install" "javascripting"
47735 error node v8.10.0
47736 error npm  v3.5.2
47737 error path /home/me/fun/js/node_modules/.staging/colors-94400b4a
47738 error code EACCES
47739 error errno -13
47740 error syscall rename
47741 error Error: EACCES: permission denied, rename '/home/me/fun/js/node_modules/.staging/colors-94400b4a' -> '/home/me/fun/js/node_modules/colors'
47741 error     at destStatted (/usr/share/npm/lib/install/action/finalize.js:25:7)
47741 error     at FSReqWrap.oncomplete (fs.js:152:21)
47741 error
47741 error Error: EACCES: permission denied, rename '/home/me/fun/js/node_modules/.staging/colors-94400b4a' -> '/home/me/fun/js/node_modules/colors'
47741 error  Error: EACCES: permission denied, rename '/home/me/fun/js/node_modules/.staging/colors-94400b4a' -> '/home/me/fun/js/node_modules/colors'
47741 error     at destStatted (/usr/share/npm/lib/install/action/finalize.js:25:7)
47741 error     at FSReqWrap.oncomplete (fs.js:152:21)
47741 error
47741 error Error: EACCES: permission denied, rename '/home/me/fun/js/node_modules/.staging/colors-94400b4a' -> '/home/me/fun/js/node_modules/colors'
47742 error Please try running this command again as root/Administrator.
47743 verbose exit [ -13, true ]
```

**Comment by ledsun** [comment]
How about using nvm to install node.js?

The following documents published by Microsoft may be helpful.
I don't have a Windows environment so I'm not sure if this will work.
https://docs.microsoft.com/en-us/windows/nodejs/setup-on-wsl2#install-nvm-nodejs-and-npm

**Comment by a0viedo** [comment]
if you install node with sudo, all npm globals will need sudo as well (it is not recommended though, nvm would be best).

**Comment by philshem** [comment]
> How about using nvm to install node.js?
> 
> The following documents published by Microsoft may be helpful.
> I don't have a Windows environment so I'm not sure if this will work.
> https://docs.microsoft.com/en-us/windows/nodejs/setup-on-wsl2#install-nvm-nodejs-and-npm

Thanks! These steps for me are working on WSL

```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
nvm install node
nvm use node
npm install -g javascripting
javascripting
```
